<?xml version="1.0" encoding="UTF-8"?>
<!-- Generated by org.testng.reporters.JUnitXMLReporter -->
<testsuite ignored="1" hostname="MSI" failures="1" tests="1" name="slider" time="10.054" errors="0" timestamp="2022-10-26T22:41:05 GMT+03:00">
  <testcase classname="slider.HomePageSliderTests" name="testSliderIcons" time="1.278">
    <failure type="java.lang.AssertionError" message="Next icon not working expected [2] but found [1]">
      <![CDATA[java.lang.AssertionError: Next icon not working expected [2] but found [1]
at slider.HomePageSliderTests.testSliderIcons(HomePageSliderTests.java:17)
at java.base/java.util.ArrayList.forEach(ArrayList.java:1540)
at java.base/java.util.concurrent.FutureTask.run(FutureTask.java:264)
at java.base/java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1128)
at java.base/java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:628)
at java.base/java.lang.Thread.run(Thread.java:834)
... Removed 22 stack frames]]>
    </failure>
  </testcase> <!-- testSliderIcons -->
  <testcase classname="slider.HomePageSliderTests" name="testSliderImageClick" time="0.0">
    <ignored/>
  </testcase> <!-- testSliderImageClick -->
</testsuite> <!-- slider -->
